CREATE TABLE PRODUTO (
    ID SERIAL,
    NOME VARCHAR(300),
    VALOR NUMERIC(10,2),
    DESCRICAO VARCHAR(1000),
        
    CONSTRAINT PRODUTO_KEY_ID PRIMARY KEY (ID)
 );
 
    
    CREATE TABLE SERVICO (
    ID SERIAL,
    TIPO VARCHAR(300),
    VALOR NUMERIC(10,2),
    DESCRICAO VARCHAR(1000),
        
    CONSTRAINT SERVICO_KEY_ID PRIMARY KEY (ID)
    );


CREATE TABLE TIPO_FUNCIONARIO (
    ID SERIAL,
    TERMO VARCHAR(100) ,
        
    CONSTRAINT TIPO_FUNCIONARIO_KEY_ID PRIMARY KEY (ID)
    );
CREATE TABLE ENDERECO (
    ID SERIAL,
    RUA VARCHAR(256),
    BAIRRO VARCHAR(256),
    CIDADE VARCHAR(256),
    CEP VARCHAR(10) ,
        
    CONSTRAINT ENDERECO_KEY_ID PRIMARY KEY (ID)
    );
    

CREATE TABLE FUNCIONARIO (
    ID SERIAL,
    NOME VARCHAR(300),
    NASCIMENTO DATE,
    EMAIL VARCHAR(256),
    CELULAR VARCHAR(15),
    ENDERECO INTEGER REFERENCES ENDERECO (ID),
    CPF VARCHAR(15),
    MATRICULA VARCHAR(20),
    SENHA VARCHAR(20),
    SIUACAO BOOL,
    TIPO_FUNCIONARIO INTEGER REFERENCES TIPO_FUNCIONARIO (ID),
    
    CONSTRAINT FUNCIONARIO_KEY_ID PRIMARY KEY (ID)   
);


    CREATE TABLE CLIENTE (
    ID SERIAL,
    NOME VARCHAR(300),
    NASCIMENTO DATE,
    EMAIL VARCHAR(256),
    CELULAR VARCHAR(15),
    ENDERECO INTEGER REFERENCES ENDERECO (ID),
    CPF VARCHAR(15),
    CODIGO INTEGER,
            
    CONSTRAINT CLIENTE_KEY_ID PRIMARY KEY (ID)
    );

CREATE TABLE EVENTO (
    ID SERIAL,
    QUANTIDADE_CONVIDADOS INTEGER,
    LOCAL INTEGER REFERENCES ENDERECO(ID),
    CLIENTE INTEGER REFERENCES CLIENTE (ID),
    VALOR NUMERIC(10,2),
        
    CONSTRAINT EVENTO_KEY_ID PRIMARY KEY (ID)
    );

CREATE TABLE SERVICO_CONTRATADO (
    ID SERIAL,
    QUANTIDADE INTEGER,
    SERVICO INTEGER REFERENCES SERVICO(ID),
    EVENTO INTEGER REFERENCES EVENTO (ID),
    
      CONSTRAINT SERVICO_CONTRATADO_KEY_ID PRIMARY KEY (ID)
   
    );

CREATE TABLE PRODUTO_QUANTIDADE(
    ID SERIAL,
    QUANTIDADE INTEGER,
    EVENTO INTEGER REFERENCES EVENTO (ID),
    PRODUTO INTEGER REFERENCES PRODUTO (ID),
    
        
    CONSTRAINT PRODUTO_QUANTIDADE_KEY_ID PRIMARY KEY (ID)
    
    );

CREATE TABLE AGENDA (
    ID SERIAL,
    DATA DATE,
    EVENTO INTEGER REFERENCES EVENTO(ID),
    CONSTRAINT AGENDA_KEY_ID PRIMARY KEY (ID)
    );
    